id: default


paths:
  rails:
    - rails/topics.co

instructions:
  - type: general
    content: |
      Below is a conversation between a personal shopping assistant and
      a user.

models:
  - type: main
    engine: openai
    model: qwen2-1.5b-instruct
    parameters:
      base_url:  "http://127.0.0.1:1234/v1"
      api_key:   "lm-studio"
      temperature: 0.7
      max_tokens: 1000
      timeout:    60


# nemoguardrails server --config guardrails --default-config-id default
