services:
    backend:
        build: .
        container_name: mlops-backend
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"] 
            interval: 30s          
            timeout: 10s           
            retries: 3         
            start_period: 10s 
        volumes:
          - ../DATA:/DATA
        ports:
            - 8000:8000
        extra_hosts:
            - "localhost:0.0.0.0"